# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0129e63b4995b672ac9280715f8b427412d08c7f131549de9492aeebebe1fc7606a68d8e01c6738b8749889f14d95737c8b54037b45740f2ad8de4f47c43d8ba

test:
  secret_key_base: 7115b2c5d5162a413d1a9863c5b18f665a52b8e882a226b560f10a68e6479b38bd03465d024f5cd533a83a28c70afce003bdace055f374f0350486eccdd5b393

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
